cc -O2 -o vmw5 vmw5.c -I/usr/X11R6/include -L/usr/X11R6/lib -lGL -lGLU -lX11
echo "On a 64 bit machine, try -L/usr/X11R6/lib64 instead"
echo "When running this program, the original source file must be in"
echo "  the same directory as the executable, with a filename of "
echo "  executable name + .c"
